# Expected Payment.  Can be more than one options.
payments:
  - amount: 1000
    token: TWT
    address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
  - amount: 5
    token: BNB
    address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
payment:
  # The tolerance for slightly lower amount, in percentage.  Valid range: 95 -- 100
  amountTolerancePct: 96
# Message templates
message:
  initial: |
    Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
    💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
    See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
    \nPlease pay  **$PAY1_AMOUNT $PAY1_CURRENCY**  with the memo **$PAY1_MEMO**  to the address `$PAY1_ADDRESS`.
    Alternatively, $PAY2_AMOUNT $PAY2_CURRENCY is also accepted (same memo & address).
    \n$QR1_SIMPLE
    \n*Notes*:
    * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
    * New tokens without significant usage are rejected, see criteria mentioned above.
    * One PR should be for a single project; PR's with more than 10 logos will be rejected.
    * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
    * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
    * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
  notReceived: Fee has not been received yet (or not fully).\n\n$TX_LIST
  received: |
    Fee is PAID, fantastic!  Thanks!
    \nThe PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
    Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation).  See the [assets FAQ](https://github.com/trustwallet/assets#faq). 
    (@zachzwei, @Cryptocool1: please take note.)
    \n([$PAID_AMOUNT $PAID_CURRENCY]($PAID1_EXPLORERLINK))
  reviewCreated: Fee paid, review added.
  reviewed: Review is not needed any more, no more fee required.
  reminder: |
    $USER, kind reminder:  please pay fee:  **$PAY1_AMOUNT $PAY1_CURRENCY**  with the memo **$PAY1_MEMO**  to the address `$PAY1_ADDRESS`.
    Alternatively, $PAY2_AMOUNT $PAY2_CURRENCY is also accepted (same memo & address).
    \n$QR1_SIMPLE
    See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
  oldClosing: |
    This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
    Do NOT send payments for closed PR, as the fee may by lost!
label:
  requested: 'Payment Status: Requested'
  paid: 'Payment Status: Paid'
user:
  assignOnPay: zachzwei,Cryptocool1,cryptomanz
  # if set to 1 comments from not allowed users are deleted.  Only comments from the PR creator or collaborators are allowed
  deleteComments: 1
  collaborators: zachzwei,Iamdeadlyz,catenocrypt,vikmeup,hewigovens,Cryptocool1,cryptomanz
timeout:
  maxAgeCloseHours: 48
  maxIdleRemindHours: 22
