CREATE TYPE "LeadStage" AS ENUM ('LEAD','QUALIFIED','CONSULTATION','VISA_PLANNING','PROPERTY_SEARCH','PROPERTY_SHORTLIST','PROPERTY_VIEWING','OFFER_SUBMITTED','CONTRACT_SIGNED','DEPOSIT_PAID','CLOSED','POST_PURCHASE');
CREATE TYPE "TaskStatus" AS ENUM ('TODO','IN_PROGRESS','DONE','CANCELLED');
CREATE TABLE retirees (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, phone TEXT, nationality TEXT, country TEXT, age INT, marital_status TEXT, retirement_date TIMESTAMPTZ, relocation_date TIMESTAMPTZ, relocation_urgency TEXT, lead_stage "LeadStage" NOT NULL DEFAULT 'LEAD', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE financial_profiles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID UNIQUE NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, net_worth_range TEXT, annual_income_range TEXT, investment_budget DECIMAL, cash_available DECIMAL, financing_required BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE visa_requirements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID UNIQUE NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, visa_type TEXT, visa_status TEXT, application_stage TEXT, notes TEXT);
CREATE TABLE property_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID UNIQUE NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, property_type "PropertyType", preferred_locations TEXT[] NOT NULL DEFAULT '{}', min_bedrooms INT, max_bedrooms INT, min_budget DECIMAL, max_budget DECIMAL, private_pool_required BOOLEAN NOT NULL DEFAULT false, walkability_importance INT, airport_importance INT);
CREATE TABLE healthcare_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID UNIQUE NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, mobility_needs TEXT, specialist_requirements TEXT, preferred_hospital TEXT, long_term_care_interest BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE lifestyle_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID UNIQUE NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, golf BOOLEAN NOT NULL DEFAULT false, boating BOOLEAN NOT NULL DEFAULT false, pickleball BOOLEAN NOT NULL DEFAULT false, tennis BOOLEAN NOT NULL DEFAULT false, fitness BOOLEAN NOT NULL DEFAULT false, beach_lifestyle BOOLEAN NOT NULL DEFAULT false, church BOOLEAN NOT NULL DEFAULT false, volunteer_work BOOLEAN NOT NULL DEFAULT false, social_clubs BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE travel_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID UNIQUE NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, trips_per_year INT, airport_convenience_importance INT, preferred_airlines TEXT, family_visit_frequency TEXT);
CREATE TABLE activities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, activity_type TEXT NOT NULL, activity_date TIMESTAMPTZ NOT NULL, activity_notes TEXT);
CREATE TABLE tasks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT, due_date TIMESTAMPTZ, status "TaskStatus" NOT NULL DEFAULT 'TODO');
CREATE TABLE notes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retiree_id UUID NOT NULL REFERENCES retirees(id) ON DELETE CASCADE, note_text TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE email_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT UNIQUE NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, category TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX retirees_lead_stage_idx ON retirees(lead_stage); CREATE INDEX activities_retiree_id_activity_date_idx ON activities(retiree_id, activity_date); CREATE INDEX tasks_retiree_id_due_date_idx ON tasks(retiree_id, due_date); CREATE INDEX notes_retiree_id_created_at_idx ON notes(retiree_id, created_at);
INSERT INTO email_templates (name, subject, body, category) VALUES
('Welcome','Welcome to TRELA','Dear {{first_name}}, welcome to your Thailand retirement property advisory journey.','onboarding'),
('Consultation Booking','Schedule your TRELA consultation','Dear {{first_name}}, choose a consultation time so we can refine your retirement and relocation priorities.','consultation'),
('Property Recommendations','Your curated Phuket property recommendations','Dear {{first_name}}, we prepared a shortlist of properties matched to your lifestyle, healthcare, and budget needs.','recommendations'),
('Visa Checklist','Thailand retirement visa checklist','Dear {{first_name}}, here is your current visa planning checklist and next documentation steps.','visa'),
('Property Viewing Confirmation','Property viewing confirmation','Dear {{first_name}}, your property viewing itinerary is confirmed.','viewing');
