import { prisma } from '@/lib/prisma';
export default async function Dashboard() {
  const [projects, properties, avg, areas, units, handovers, leads, activeClients, pipeline, visa, followUps] = await Promise.all([
    prisma.project.count(), prisma.property.count(), prisma.propertyScores.aggregate({ _avg: { retirementScore: true } }), prisma.project.groupBy({ by: ['location'], _count: true, take: 8 }), prisma.project.aggregate({ _sum: { unitsAvailable: true } }), prisma.project.findMany({ where: { handoverDate: { gte: new Date() } }, take: 6, orderBy: { handoverDate: 'asc' } }),
    prisma.retiree.count(), prisma.retiree.count({ where: { leadStage: { notIn: ['LEAD', 'CLOSED', 'POST_PURCHASE'] } } }), prisma.financialProfile.aggregate({ _sum: { investmentBudget: true } }), prisma.visaRequirement.count({ where: { visaStatus: { not: null } } }), prisma.task.findMany({ where: { status: { not: 'DONE' }, dueDate: { gte: new Date() } }, include: { retiree: true }, take: 6, orderBy: { dueDate: 'asc' } })
  ]);
  const cards = [['Total Leads', leads], ['Active Clients', activeClients], ['Pipeline Value', `฿${Number(pipeline._sum.investmentBudget ?? 0).toLocaleString()}`], ['Properties Matched', properties], ['Visa Applications', visa], ['Upcoming Follow-Ups', followUps.length], ['Total Projects', projects], ['Average Retirement Score', Math.round(avg._avg.retirementScore ?? 0)], ['Units Available', units._sum.unitsAvailable ?? 0]];
  return <section><h2 className="text-3xl font-bold">TRLA Advisory Dashboard</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{cards.map(([k, v]) => <div className="card p-5" key={k}><p className="text-sm text-slate-500">{k}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-3"><div className="card p-5"><h3 className="font-bold">Properties by Area</h3>{areas.map((a) => <p className="mt-3 flex justify-between" key={a.location}><span>{a.location}</span><b>{a._count}</b></p>)}</div><div className="card p-5"><h3 className="font-bold">Upcoming Handovers</h3>{handovers.map((h) => <p className="mt-3 flex justify-between" key={h.id}><span>{h.projectName}</span><span>{h.handoverDate?.toISOString().slice(0, 10)}</span></p>)}</div><div className="card p-5"><h3 className="font-bold">Upcoming Follow-Ups</h3>{followUps.map((t) => <p className="mt-3" key={t.id}><b>{t.title}</b><br/><span className="text-sm text-slate-500">{t.retiree.firstName} {t.retiree.lastName} · {t.dueDate?.toISOString().slice(0, 10)}</span></p>)}</div></div></section>;
}
